const version = 'v1';
module.exports = {
    CUSTOMER: `/${version}/auth/customers`,
    ADMIN: `/${version}/auth/admins`,
    PROVIDER: `/${version}/auth/providers`,
    USER: `/${version}/auth/users`,
    SERVICE: `/${version}/services`,
    PRODUCT: `/${version}/products`,
    RATING: `/${version}/ratings`,
    PROMOTIONS: `/${version}/promotions`,
    CATEGORY: `/${version}/categories`,
    NOTIFICATION: `/${version}/notifications`,
    CAR: `/${version}/cars`,
    ESTIMATE: `/${version}/estimates`,
    BOOKING: `/${version}/bookings`,
    ORDER: `/${version}/orders`,
    CHAT: `/${version}/chat`,
    BULK_EMAIL: `/${version}/bulkEmails`,
    OFFER: `/${version}/offers`,
    SETTING: `/${version}/settings`,
    ABOUT: `/${version}/about`,
    SLIDER: `/${version}/sliders`,
    HEADER: `/${version}/header`,
    FOOTER: `/${version}/footer`,
    TRANSACTION: `/${version}/transactions`,
    PRIVACYPOLICY: `/${version}/privacy-policy`,
    TERMCONDITION: `/${version}/term-condition`,
    CONTACTREQ: `/${version}/contact-req`,
    INVITES: `/${version}/invites`,
    WALLET: `/${version}/wallet`,
    WALLET_TRANS: `/${version}/wallet-transactions`,
    DISPUTE: `/${version}/disputes`,
    CURRENCY: `/${version}/currencies`,
    OFFICE: `/${version}/offices`,
};
